[workspace]
resolver = "2"
members = [
    "crates/nvim-core",
    "crates/editor-surface",
    "crates/git-core",
    "crates/neobeam",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Neobeam"]

[profile.release]
opt-level = 'z'
lto = "thin"
codegen-units=1
strip=true
