[package]
name = "editor-surface"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.102"
bytemuck = { version = "1.25.0", features = ["derive"] }
etagere = "0.3.0"
fontdb = "0.23.0"
fontdue = "0.9.3"
nvim-core = { version = "0.1.0", path = "../nvim-core" }
pollster = "0.4.0"
tracing = "0.1.44"
wgpu = "29.0.3"
winit = "0.30.13"
